### ISSUE TITLE
Website TODO

### ISSUE THREAD

**Issue by mrfoto** [SloveniaRUG/SloveniaRUG.github.io#15]
Please open a separate PR for each of these:
- [x] fix mobile newsletter subscription @mfilej 
- [ ] target _blank on external links (has to be GA tracked!)
- [ ] fix mobile menu dropdown
- [ ] prettify them tables http://www.rug.si/donations/
- [ ] custom 404 like we [had before](https://github.com/SloveniaRUG/SloveniaRUG.github.io/blob/20b9a72196e0bd69d2885fe79ce3ae87fc9ba9a4/404.html)
- [ ] A place for sponsors / partners / supporters / advertisers
- [ ] Add OpenGraph meta-data and test with [Facebook Linter](https://developers.facebook.com/tools/debug/)

Anyone can contribute, including **you**

**Comment by mrfoto** [comment]
Moved into separate issues that can be assigned to people.
